services:
  bot:
    build:
      context: .
    env_file:
      - .env
    restart: always
    environment:
      - ENVRIONMENT=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
