name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "*.py"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
        with:
          version-file: "pyproject.toml"
